apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-sc
spec:
  storageClassName: ase-node-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi